language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
  - "3.7"

# # command to install dependencies\
# cache: pip
# sudo: false
# virtualenv:
#   system_site_packages: true
# addons:
#   apt:
#     packages:
#       - libatlas-dev
#       - libatlas3gf-base
#       - libblas-dev
#       - liblapack-dev
#       - python-matplotlib
#       - gfortran
#       - python-tk
# install:
#   - conda create -n meegkit --yes pip python=$PYTHON
#   - source activate meegkit
#   - conda install --yes --quiet numpy scipy nose coverage
#   - pip install codecov
#   - python setup.py build install
# # Setup anaconda
# before_install:
#   - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#   - chmod +x miniconda.sh
#   - ./miniconda.sh -b -p /home/travis/miniconda
#   - export PATH=/home/travis/miniconda/bin:$PATH
#   - conda update --yes --quiet conda
#   # We need to create a (fake) display on Travis (allows Mayavi tests to run)
#   - export DISPLAY=:99.0
#   - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f environment.yml
  - source activate meegkit
  - python setup.py install

# # command to run tests
# script: nosetests  --with-coverage --cover-package=meegkit
# script: nosetests
# after_success:
#   - codecov
