# run: conda env create --file environment.yml
name: meegkit
dependencies:
- python>=3.5
- pip
- numpy
- scipy
- matplotlib
- scikit-learn
- sphinx
- joblib
- numpydoc
- flake8
- pip:
  - pytest
  - pytest-cov
  - codecov
  - codespell
  - pydocstyle
  - sphinx-gallery
  - tqdm
